@echo off
SET CONFIG_VERSION=0.9.0

IF "%PIDMD_ROOT%"=="" CALL :LOG-ERRO EVN ERROR! & exit /b

IF NOT EXIST "%PIDMD_ROOT%\CCS.BAT" CALL :LOG-ERRO NOT FOUND CCS! & exit /b

SET CONFIG_CONFIG_FILEPATH=%1
SET CONFIG_CONFIG_PATH=%2
SET CONFIG_CONFIG_KEY_VAL=%3

IF /I "%1"=="/HELP" GOTO HELP
IF /I "%1"=="#SRV" CALL :#SRV %2 %3 %4
IF /I "%1"=="#PIDMD" CALL :#PIDMD

REM echo.%CONFIG_CONFIG_FILEPATH% %CONFIG_CONFIG_PATH% %CONFIG_CONFIG_KEY_VAL%

IF NOT EXIST "%CONFIG_CONFIG_FILEPATH%" (CALL :LOG-ERRO NOT FOUND CONFIG: %CONFIG_CONFIG_FILEPATH% & EXIT /B)

for /F "tokens=1,2 delims=," %%1 in ("%CONFIG_CONFIG_PATH:/=,%") do SET CONFIG_CONFIG_BLK=%%1 & SET CONFIG_CONFIG_KEY=%%2

CALL :LOGHE-INFO %CONFIG_CONFIG_FILEPATH%: %CONFIG_CONFIG_PATH% SET %CONFIG_CONFIG_KEY_VAL%
REM echo.%CONFIG_CONFIG_BLK%

SET CONFIG_CENTER_FILE=%CONFIG_CONFIG_FILEPATH%

IF /i NOT "%CONFIG_CONFIG_BLK%"=="#NONE" (
	call ccs.bat /key-nblk-changeval %CONFIG_CONFIG_KEY% %CONFIG_CONFIG_KEY_VAL%
	GOTO :CONFIG-END
)
	
CALL ccs.bat /key-changeval %CONFIG_CONFIG_BLK% %CONFIG_CONFIG_KEY% %CONFIG_CONFIG_KEY_VAL%


:CONFIG-END
SET CONFIG_CENTER_FILE=
SET CONFIG_CONFIG_FILEPATH=
EXIT /B

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

:#PIDMD
	REM SYSTEM.INI
	SET CONFIG_CONFIG_FILEPATH=%PIDMD_ROOT%system.ini
EXIT /B


:#SRV
	REM SRVFILE
	SET CONFIG_CONFIG_FILEPATH=%PIDMD_SRV%%1
	SET CONFIG_CONFIG_PATH=#NONE/%2
	SET CONFIG_CONFIG_KEY_VAL=%3
EXIT /B

:HELP
	ECHO.CALL CONFIG.cmd /HELP
	ECHO.CALL CONFIG.cmd ^<PATH^> {^<BLOCK^>^|#NONE}/^<KEY^> ^<NEW_VAL^>
	ECHO.CALL CONFIG.cmd #PIDMD ^<BLOCK^>/^<KEY^> ^<NEW_VAL^>
	ECHO.CALL CONFIG.cmd #SRV ^<SRV:name^> ^<KEY^> ^<NEW_VAL^>
	ECHO.
	ECHO.v%CONFIG_VERSION%
EXIT /B

:LOGHE-INFO
	SET _LOG_STR=%*
	SET _LOG_STR=%_LOG_STR: =#sp#%
	CALL LOGHE.CMD CONFIG INFO %_LOG_STR%
	SET _LOG_STR=
EXIT /B

:LOGHE-WARN
	SET _LOG_STR=%*
	SET _LOG_STR=%_LOG_STR: =#sp#%
	CALL LOGHE.CMD CONFIG WARN %_LOG_STR%
	SET _LOG_STR=
EXIT /B

:LOGHE-ERRO
	SET _LOG_STR=%*
	SET _LOG_STR=%_LOG_STR: =#sp#%
	CALL LOGHE.CMD CONFIG ERRO %_LOG_STR%
	SET _LOG_STR=
EXIT /B

:LOG-INFO
	SET _LOG_STR=%*
	SET _LOG_STR=%_LOG_STR: =#sp#%
	CALL LOG.CMD CONFIG INFO %_LOG_STR%
	SET _LOG_STR=
EXIT /B

:LOG-WARN
	SET _LOG_STR=%*
	SET _LOG_STR=%_LOG_STR: =#sp#%
	CALL LOG.CMD CONFIG WARN %_LOG_STR%
	SET _LOG_STR=
EXIT /B

:LOG-ERRO
	SET _LOG_STR=%*
	SET _LOG_STR=%_LOG_STR: =#sp#%
	CALL LOG.CMD CONFIG ERRO %_LOG_STR%
	SET _LOG_STR=
EXIT /B
